services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: truhire-opensearch

    environment:
      - cluster.name=truhire-cluster
      - node.name=truhire-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    ports:
      - "9200:9200"
      - "9600:9600"

    volumes:
      - opensearch_data:/usr/share/opensearch/data

    networks:
      - truhire-network


  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: truhire-dashboards

    ports:
      - "5601:5601"

    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"

    networks:
      - truhire-network

    depends_on:
      - opensearch


volumes:
  opensearch_data:


networks:
  truhire-network:
    driver: bridge