from typing import List, Optional
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    APP_NAME: str = "TruHire"
    APP_ENV: str = "development"
    DEBUG: bool = True

    DATABASE_URL: str = Field(default="sqlite:///./truhire.db")

    SECRET_KEY: str = Field(default="truhire_dev_secret_key_change_me_in_production")
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440

    # DGX/vLLM: OpenAI-compatible server. Example SSH tunnel:
    # ssh -L 8000:localhost:8000 -L 6333:localhost:6333 truviq_domain@192.168.0.143
    VLLM_BASE_URL: str = "http://localhost:8000/v1"
    VLLM_API_KEY: Optional[str] = None
    VLLM_MODEL: Optional[str] = None
    VLLM_EMBEDDING_MODEL: Optional[str] = None
    VLLM_TIMEOUT: float = 120.0

    # Proper vector database: Qdrant, normally exposed by the 6333 SSH tunnel.
    QDRANT_URL: str = "http://localhost:6333"
    QDRANT_API_KEY: Optional[str] = None
    QDRANT_COLLECTION: str = "truhire_candidate_vectors"
    QDRANT_DISTANCE: str = "Cosine"

    # OpenSearch is retained for lexical/BM25 retrieval in the hybrid pipeline.
    OPENSEARCH_URL: str = "http://localhost:9200"
    OPENSEARCH_USER: Optional[str] = None
    OPENSEARCH_PASSWORD: Optional[str] = None
    OPENSEARCH_INDEX: str = "truhire_candidates_v2"

    # Embeddings are generated by vLLM; no mock embedding fallback.
    EMBEDDING_PROVIDER: str = "vllm"
    EMBEDDING_MODEL: Optional[str] = None
    EMBEDDING_DIM: int = 768

    INGEST_BATCH_SIZE: int = 50
    MAX_UPLOAD_MB: int = 15
    STORAGE_DIR: str = "./uploads"

    SEARCH_TOP_N: int = 20
    SEARCH_MAX_TOP_N: int = 100
    HYBRID_VECTOR_WEIGHT: float = 0.60
    HYBRID_LEXICAL_WEIGHT: float = 0.40
    HYBRID_RRF_K: int = 60
    SEARCH_CANDIDATE_MULTIPLIER: int = 5

    SEMANTIC_WEIGHT: float = 0.45
    SKILL_WEIGHT: float = 0.35
    BASELINE_SCORE: float = 0.20
    EXPERIENCE_PENALTY: float = 0.10
    EDUCATION_PENALTY: float = 0.05

    ANALYTICS_TOP_SKILLS: int = 20
    CACHE_TTL_QUERY: int = 30

    CORS_ORIGINS: List[str] = [
        "http://localhost:5173", "http://localhost:3000",
        "http://127.0.0.1:5173", "http://127.0.0.1:3000"
    ]


settings = Settings()
